[app]
front_url = "http://localhost:5173"
back_url = "http://localhost:4000"

[database]
database_url = "postgres://myuser:mysecretpassword@localhost/t2ris"

[jwt]
jwt_access_secret = "access_access_access_access_access_access_access_access_access_access"
jwt_refresh_secret = "refresh_refresh_refresh_refresh_refresh_refresh_refresh_refresh_refresh"
# 1 * 60
jwt_access_time = 60
# 1 * 60 * 60 * 24
jwt_refresh_time = 86400

[sec]
aes128key = "0123456789abcdef"

[redis]
redis_url = "redis://@localhost"

[oauth2]
oauth2_google_client_id = "???"
oauth2_google_client_secret = "???"
